name: Auto-merge Pull request
on: [push, pull_request, workflow_dispatch]

jobs:
  auto_merge:
    runs-on: ubuntu-latest
    name: A job to say hello
    permissions:
      pull-requests: write
      contents: write
    steps:
      - name: Try to auto merge PR
        uses: funSamy/auto-merge-action@v1.1.0
        id: auto-merge
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
          merge-method: merge

      - name: Merge results
        run: |
          echo sha: ${{ env.sha }}
          echo merged: ${{ env.merged }}
          echo message: ${{ env.message }}
        env:
          sha: ${{ steps.auto-merge.outputs.sha }}
          merged: ${{ steps.auto-merge.outputs.merged }}
          message: ${{ steps.auto-merge.outputs.message }}
